package com.engfred.musicplayer.feature_dj_mix.data.sampler

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import android.util.Log
import androidx.media3.common.util.UnstableApi
import com.engfred.musicplayer.feature_dj_mix.data.crossfade.CrossfadeEngine
import com.engfred.musicplayer.feature_dj_mix.data.crossfade.CrossfadeEngineState
import com.engfred.musicplayer.feature_dj_mix.data.crossfade.MixStrategy
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Low-latency DJ sampler engine built on Android's [SoundPool].
 *
 * ── Two trigger modes ────────────────────────────────────────────────────────
 * 1. AUTO   — observes [CrossfadeEngine.state] and fires samples automatically
 *             at crossfade lifecycle events (start, mid-mix, completion).
 *             Controlled by [isAutoSamplerEnabled].
 * 2. MANUAL — the DJ Mix UI exposes a pad grid; tapping a pad calls
 *             [triggerSample] directly.
 *
 * ── TEST BUILD ────────────────────────────────────────────────────────────────
 * Decision space is reduced to HARMONIC + WIDE_TRANSITION only.
 * TRANSPARENT / SMOOTH / POWER_MIX auto-trigger branches are COMMENTED OUT.
 *
 * Orphaned samples (previously only triggered by the removed strategies) have
 * been redistributed:
 *   • Promoted to manual pads in SampleId (isManual = true) — always tappable.
 *   • WHITE_NOISE_UP and IMPACT_HIT added as extra mid triggers for HARMONIC.
 *   • RISER_SWEEP added as an extra mid trigger for WIDE_TRANSITION.
 *   • AIR_HORN promoted to WIDE_TRANSITION drop (was SMOOTH/POWER_MIX drop).
 *
 * To restore full 5-strategy behaviour:
 *   1. Un-comment all [STRATEGY TEST] blocks here.
 *   2. Un-comment MixStrategy entries in CrossfadeModels.kt.
 *   3. Un-comment decision branches in MixDecisionEngine.kt.
 *   4. Revert isManual = false on synthesized samples in SampleId.kt.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * ── Auto-trigger map (TEST BUILD — 2 strategies) ─────────────────────────────
 *
 *  Strategy          │ On START       │ Mid 1               │ Mid 2               │ On DROP
 *  ──────────────────┼────────────────┼─────────────────────┼─────────────────────┼──────────
 *  HARMONIC          │ REWIND_SWEEP   │ WHITE_NOISE_UP (40%)│ IMPACT_HIT    (70%) │ CROWD_HEY
 *  WIDE_TRANSITION   │ SIREN          │ RISER_SWEEP    (30%)│ STUTTER_HIT   (45%) │ AIR_HORN
 *  ─────────────────────────────────────────────────────────────────────────────────────────
 *  Session start     │ AIR_HORN (once, fired by DjMixService on first play)
 *
 * ── Original auto-trigger map (FULL 5-strategy — for reference) ──────────────
 *
 *  Strategy          │ On START        │ Mid                       │ On DROP
 *  ──────────────────┼─────────────────┼───────────────────────────┼────────────────────
 *  TRANSPARENT       │ DJ_SCRATCH      │ —                         │ — (silence = effect)
 *  SMOOTH            │ RISER_SWEEP     │ STUTTER_HIT    (50%)      │ AIR_HORN
 *  POWER_MIX         │ WHITE_NOISE_UP  │ IMPACT_HIT     (35%)      │ AIR_HORN
 *  HARMONIC          │ REWIND_SWEEP    │ —                         │ CROWD_HEY
 *  WIDE_TRANSITION   │ SIREN           │ STUTTER_HIT    (45%)      │ CROWD_HEY
 *  ─────────────────────────────────────────────────────────────────────────────────────────
 *
 * ── Architecture notes ───────────────────────────────────────────────────────
 * - [SoundPool] pre-decodes all audio to raw PCM at load time, so each
 *   [triggerSample] fires in < 10 ms — fast enough to feel "live".
 * - Up to [MAX_STREAMS] sounds can overlap simultaneously.
 * - Synthesized samples are generated by [SynthesizedSampleGenerator] on a
 *   background coroutine and loaded into SoundPool once their WAV file is ready.
 * - [SamplerEngine] is a @Singleton; call [initialize] from [DjMixService.onCreate]
 *   and [release] from [DjMixService.releaseAndStop] / [DjMixService.onDestroy].
 * - Call [onSessionStarted] from [DjMixService] when the first track begins playing.
 */
@UnstableApi
@Singleton
class SamplerEngine @Inject constructor(
    @param:ApplicationContext private val context: Context,
    private val crossfadeEngine: CrossfadeEngine,
    private val synthesizer: SynthesizedSampleGenerator
) {

    companion object {
        private const val TAG         = "SamplerEngine"
        private const val MAX_STREAMS = 6

        // ── Per-strategy mid-crossfade trigger thresholds ─────────────────────
        // These intentionally differ from the bass-kill EQ thresholds in
        // MixDecisionEngine — the sampler fires at a musically optimal moment,
        // the EQ at a technical one.

        // [TEST BUILD] SMOOTH / POWER_MIX thresholds kept for reference only.
        // private const val MID_FRACTION_SMOOTH          = 0.50f  // [STRATEGY TEST]
        // private const val MID_FRACTION_POWER_MIX       = 0.35f  // [STRATEGY TEST]

        // HARMONIC mid triggers (new in test build)
        private const val MID_FRACTION_HARMONIC_1       = 0.40f  // WHITE_NOISE_UP — builds tension
        private const val MID_FRACTION_HARMONIC_2       = 0.70f  // IMPACT_HIT     — punch at lock moment

        // WIDE_TRANSITION mid triggers (RISER_SWEEP added; STUTTER_HIT kept at original fraction)
        private const val MID_FRACTION_WIDE_TRANSITION_1 = 0.30f  // RISER_SWEEP  — builds during valley
        private const val MID_FRACTION_WIDE_TRANSITION_2 = 0.45f  // STUTTER_HIT  — fills energy valley nadir

        private const val SESSION_HORN_POLL_MS    = 20L
        private const val SESSION_HORN_TIMEOUT_MS = 600L
    }

    // ── SoundPool state ───────────────────────────────────────────────────────

    private var soundPool: SoundPool? = null

    /** Maps SampleId → SoundPool sound ID returned by SoundPool.load(). */
    private val soundIds     = mutableMapOf<SampleId, Int>()

    /** Tracks which SoundPool sound IDs have fully decoded and are ready to play. */
    private val loadedSounds = mutableSetOf<Int>()

    // ── Settings ──────────────────────────────────────────────────────────────

    /** When false the engine is silent on all auto-triggers; manual pads still work. */
    var isAutoSamplerEnabled: Boolean = true

    /** Volume applied to every sample playback (0.0 – 1.0). */
    var sampleVolume: Float = 0.80f

    // ── Internal ──────────────────────────────────────────────────────────────

    private var samplerScope  = CoroutineScope(SupervisorJob() + Dispatchers.Default)
    private var observerJob: Job? = null

    @Volatile private var isInitialized = false
    @Volatile private var isReleased    = false

    /**
     * Tracks which mid-crossfade thresholds have already fired for the current
     * crossfade transition. Cleared each time isCrossfading flips false → true.
     *
     * Replaces the original single [midTriggerFiredForCurrentCrossfade] boolean now
     * that each strategy can have multiple mid triggers at different fractions.
     * Accessed only from within the sequential [observerJob] coroutine — no
     * synchronisation needed.
     */
    private val firedMidThresholds = mutableSetOf<Float>()

    val isReady: Boolean get() = isInitialized && !isReleased

    // ═════════════════════════════════════════════════════════════════════════
    // INITIALISATION / RELEASE
    // ═════════════════════════════════════════════════════════════════════════

    fun initialize() {
        if (isInitialized) return

        if (isReleased) {
            samplerScope  = CoroutineScope(SupervisorJob() + Dispatchers.Default)
            isReleased    = false
            soundIds.clear()
            loadedSounds.clear()
            firedMidThresholds.clear()
        }

        val audioAttrs = AudioAttributes.Builder()
            .setUsage(AudioAttributes.USAGE_MEDIA)
            .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
            .build()

        soundPool = SoundPool.Builder()
            .setMaxStreams(MAX_STREAMS)
            .setAudioAttributes(audioAttrs)
            .build()
            .also { pool ->
                pool.setOnLoadCompleteListener { _, soundId, status ->
                    if (status == 0) {
                        loadedSounds.add(soundId)
                        val name = soundIds.entries.firstOrNull { it.value == soundId }?.key?.name
                        Log.d(TAG, "Loaded: $name (soundId=$soundId)")
                    } else {
                        Log.e(TAG, "Load failed: soundId=$soundId status=$status")
                    }
                }
            }

        loadAllSamples()
        startAutoTriggerObserver()
        isInitialized = true
        Log.d(TAG, "initialize: SamplerEngine ready")
    }

    fun release() {
        if (isReleased) return
        isReleased = true
        observerJob?.cancel()
        samplerScope.cancel()
        soundPool?.release()
        soundPool    = null
        soundIds.clear()
        loadedSounds.clear()
        isInitialized = false
        Log.d(TAG, "release: SamplerEngine released")
    }

    // ═════════════════════════════════════════════════════════════════════════
    // SAMPLE LOADING
    // ═════════════════════════════════════════════════════════════════════════

    private fun loadAllSamples() {
        val pool = soundPool ?: return

        // ── Asset-based samples (downloaded CC0 OGG files) ────────────────────
        SampleId.entries.forEach { sampleId ->
            val path = sampleId.assetPath ?: return@forEach
            try {
                val afd     = context.assets.openFd(path)
                val soundId = pool.load(afd, 1)
                afd.close()
                if (soundId > 0) {
                    soundIds[sampleId] = soundId
                    Log.d(TAG, "Queued asset load: ${sampleId.name} → soundId=$soundId")
                } else {
                    Log.e(TAG, "SoundPool.load returned 0 for ${sampleId.name} — check asset path: $path")
                }
            } catch (e: Exception) {
                Log.e(TAG, "Asset load failed for ${sampleId.name}: ${e.message}")
            }
        }

        // ── Synthesized samples ───────────────────────────────────────────────
        samplerScope.launch(Dispatchers.IO) {
            SampleId.entries
                .filter { it.assetPath == null }
                .forEach { sampleId ->
                    try {
                        val file    = synthesizer.getOrGenerate(sampleId)
                        val soundId = pool.load(file.absolutePath, 1)
                        if (soundId > 0) {
                            soundIds[sampleId] = soundId
                            Log.d(TAG, "Queued synthesized load: ${sampleId.name} → soundId=$soundId")
                        } else {
                            Log.e(TAG, "SoundPool.load returned 0 for synthesized ${sampleId.name}")
                        }
                    } catch (e: Exception) {
                        Log.e(TAG, "Synthesized load failed for ${sampleId.name}: ${e.message}")
                    }
                }
        }
    }

    // ═════════════════════════════════════════════════════════════════════════
    // PUBLIC API
    // ═════════════════════════════════════════════════════════════════════════

    /**
     * Plays [sampleId] immediately at [sampleVolume].
     * Safe to call from any thread — SoundPool.play() is thread-safe.
     *
     * Returns the SoundPool stream ID (> 0 on success, 0 on failure).
     */
    fun triggerSample(sampleId: SampleId): Int {
        if (isReleased) return 0
        val pool    = soundPool ?: return 0
        val soundId = soundIds[sampleId] ?: run {
            Log.w(TAG, "triggerSample: ${sampleId.name} not loaded yet — skipping")
            return 0
        }
        if (soundId !in loadedSounds) {
            Log.w(TAG, "triggerSample: ${sampleId.name} still decoding — skipping")
            return 0
        }
        val vol      = sampleVolume.coerceIn(0f, 1f)
        val streamId = pool.play(soundId, vol, vol, 1, 0, 1.0f)
        Log.d(TAG, "triggerSample: ${sampleId.name} streamId=$streamId vol=$vol")
        return streamId
    }

    /**
     * Stops a specific sample stream returned by [triggerSample].
     */
    fun stopSample(streamId: Int) {
        if (isReleased || streamId <= 0) return
        soundPool?.stop(streamId)
        Log.d(TAG, "stopSample: streamId=$streamId")
    }

    /**
     * Immediately pauses ALL currently playing sample streams.
     * Does not affect the CrossfadeEngine or ExoPlayer music.
     */
    fun stopAllSamples() {
        if (isReleased) return
        soundPool?.autoPause()
        Log.d(TAG, "stopAllSamples: autoPause called")
    }

    /**
     * Called once per DJ session when the first track begins playing.
     *
     * Race-condition fix: SoundPool.load() is async. On first launch observeFirstPlay()
     * in DjMixService fires ~146ms before the OGG decoder finishes (confirmed by logcat),
     * causing triggerSample() to log "still decoding" and produce silence.
     *
     * Fix: fast-path plays immediately if already decoded (all launches after the first).
     * Slow-path polls loadedSounds every SESSION_HORN_POLL_MS until the asset is ready
     * or SESSION_HORN_TIMEOUT_MS elapses. Typical slow-path wait: 20-40ms.
     */
    fun onSessionStarted() {
        if (isReleased || !isAutoSamplerEnabled) return

        // Fast path: already loaded — play immediately.
        val soundId = soundIds[SampleId.AIR_HORN]
        if (soundId != null && soundId in loadedSounds) {
            triggerSample(SampleId.AIR_HORN)
            Log.d(TAG, "onSessionStarted: AIR_HORN fired immediately — DJ Mix is live")
            return
        }

        // Slow path: decoder hasn't finished yet — wait and retry.
        Log.d(TAG, "onSessionStarted: AIR_HORN not decoded yet — waiting (slow path)")
        samplerScope.launch {
            val startMs = System.currentTimeMillis()
            val sid     = soundIds[SampleId.AIR_HORN] ?: run {
                Log.w(TAG, "onSessionStarted: AIR_HORN has no soundId — asset load may have failed")
                return@launch
            }
            while (!isReleased) {
                if (sid in loadedSounds) {
                    triggerSample(SampleId.AIR_HORN)
                    Log.d(TAG, "onSessionStarted: AIR_HORN fired after " +
                            "${System.currentTimeMillis() - startMs}ms wait — DJ Mix is live")
                    return@launch
                }
                if (System.currentTimeMillis() - startMs > SESSION_HORN_TIMEOUT_MS) {
                    Log.w(TAG, "onSessionStarted: AIR_HORN timed out after ${SESSION_HORN_TIMEOUT_MS}ms — skipping")
                    return@launch
                }
                delay(SESSION_HORN_POLL_MS)
            }
        }
    }

    // ═════════════════════════════════════════════════════════════════════════
    // AUTO-TRIGGER OBSERVER
    // ═════════════════════════════════════════════════════════════════════════

    /**
     * Collects [CrossfadeEngine.state] on the Default dispatcher and fires samples
     * at three lifecycle points per crossfade:
     *
     *  1. **START**  — isCrossfading flips false → true
     *  2. **MID**    — crossfadeProgressFraction crosses any per-strategy threshold
     *                  (each strategy now supports multiple mid triggers)
     *  3. **DROP**   — isCrossfading flips true → false AND currentTrack.id changed
     *
     * [firedMidThresholds] ensures each threshold fires exactly once per transition
     * even if the state flow emits rapidly around the threshold value.
     */
    private fun startAutoTriggerObserver() {
        observerJob?.cancel()
        observerJob = samplerScope.launch {
            var prev: CrossfadeEngineState? = null

            crossfadeEngine.state.collect { current ->
                val previous = prev
                prev = current

                if (!isAutoSamplerEnabled) return@collect

                // ── 1. Crossfade just STARTED ─────────────────────────────────
                if (previous?.isCrossfading == false && current.isCrossfading) {
                    firedMidThresholds.clear()
                    onCrossfadeStarted(current.currentMixStrategy)
                }

                // ── 2. Mid-crossfade thresholds crossed ───────────────────────
                // Each strategy can now declare multiple (threshold, sample) pairs.
                if (current.isCrossfading) {
                    val midTriggers = midTriggersFor(current.currentMixStrategy)
                    val prevFraction = previous?.crossfadeProgressFraction ?: 0f
                    val currFraction = current.crossfadeProgressFraction

                    for ((threshold, sample) in midTriggers) {
                        if (threshold !in firedMidThresholds
                            && prevFraction < threshold
                            && currFraction >= threshold
                        ) {
                            firedMidThresholds.add(threshold)
                            triggerSample(sample)
                            Log.d(TAG, "Auto: mid-mix [${current.currentMixStrategy}] " +
                                    "@ ${(threshold * 100).toInt()}% → ${sample.name}")
                        }
                    }
                }

                // ── 3. Crossfade just COMPLETED (track changed) ───────────────
                val trackChanged = previous?.currentTrack?.id != current.currentTrack?.id
                if (previous?.isCrossfading == true && !current.isCrossfading && trackChanged) {
                    onDropCompleted(previous.currentMixStrategy)
                }
            }
        }
    }

    /**
     * Returns the ordered list of (threshold fraction, sample) pairs that should
     * auto-fire during the crossfade body for the given [strategy].
     *
     * An empty list means no mid-crossfade triggers for that strategy.
     *
     * [TEST BUILD] Each active strategy now has TWO mid triggers to make full
     * use of the sample library that was previously spread across 5 strategies.
     *
     * [STRATEGY TEST] Original single-trigger branches preserved in comments below.
     * To restore: replace this function body with the original single-pair returns.
     */
    private fun midTriggersFor(strategy: MixStrategy): List<Pair<Float, SampleId>> = when (strategy) {

        MixStrategy.HARMONIC -> listOf(
            MID_FRACTION_HARMONIC_1 to SampleId.WHITE_NOISE_UP,  // 40% — filter sweep builds tension
            MID_FRACTION_HARMONIC_2 to SampleId.IMPACT_HIT       // 70% — kick-punch as harmonic lock hits
        )
        // [STRATEGY TEST] Original HARMONIC had no mid trigger:
        // MixStrategy.HARMONIC -> null / emptyList()

        MixStrategy.WIDE_TRANSITION -> listOf(
            MID_FRACTION_WIDE_TRANSITION_1 to SampleId.RISER_SWEEP,  // 30% — riser builds through valley
            MID_FRACTION_WIDE_TRANSITION_2 to SampleId.STUTTER_HIT   // 45% — stutter fills energy nadir
        )
        // [STRATEGY TEST] Original WIDE_TRANSITION had one mid trigger:
        // MixStrategy.WIDE_TRANSITION -> listOf(0.45f to SampleId.STUTTER_HIT)

        // [STRATEGY TEST] Commented out — strategies not in active decision path.
        // MixStrategy.TRANSPARENT     -> emptyList()
        // MixStrategy.SMOOTH          -> listOf(MID_FRACTION_SMOOTH    to SampleId.STUTTER_HIT)
        // MixStrategy.POWER_MIX       -> listOf(MID_FRACTION_POWER_MIX to SampleId.IMPACT_HIT)
    }

    // ── Lifecycle callbacks ───────────────────────────────────────────────────

    /**
     * Fires the start-of-crossfade sample for the given strategy.
     *
     * [TEST BUILD] Only HARMONIC and WIDE_TRANSITION are active.
     * Original full-matrix branches preserved in comments below.
     */
    private fun onCrossfadeStarted(strategy: MixStrategy) {
        val sample = when (strategy) {
            // [STRATEGY TEST] Commented out — strategies not in active decision path.
            // MixStrategy.TRANSPARENT     -> SampleId.DJ_SCRATCH    // subtle scratch: "I see you"
            // MixStrategy.SMOOTH          -> SampleId.RISER_SWEEP   // rising sweep: "something's coming"
            // MixStrategy.POWER_MIX       -> SampleId.WHITE_NOISE_UP // aggressive noise sweep in

            // Downward vinyl brake: "time is shifting" — primes the ear for harmonic transition.
            MixStrategy.HARMONIC         -> SampleId.REWIND_SWEEP

            // Siren: announces the energy valley — the BPM jump IS the moment.
            MixStrategy.WIDE_TRANSITION  -> SampleId.SIREN
        }
        triggerSample(sample)
        Log.d(TAG, "Auto: crossfade started [${strategy.name}] → ${sample.name}")
    }

    /**
     * Fires the drop (end-of-crossfade) sample for the given strategy.
     *
     * [TEST BUILD] Only HARMONIC and WIDE_TRANSITION are active.
     * AIR_HORN promoted from SMOOTH/POWER_MIX drop → WIDE_TRANSITION drop.
     * Original full-matrix branches preserved in comments below.
     */
    private fun onDropCompleted(strategy: MixStrategy) {
        val sample: SampleId = when (strategy) {
            // [STRATEGY TEST] Commented out — strategies not in active decision path.
            // MixStrategy.TRANSPARENT     -> null               // silence respects the blend
            // MixStrategy.SMOOTH          -> SampleId.AIR_HORN  // classic crowd-pleaser on clean landing
            // MixStrategy.POWER_MIX       -> SampleId.AIR_HORN  // rewards crowd after bass-kill power mix

            // Crowd Hey: celebrates the harmonic lock — the crowd earned this.
            MixStrategy.HARMONIC         -> SampleId.CROWD_HEY

            // Air Horn: [TEST BUILD] promoted from SMOOTH/POWER_MIX drop.
            // Payoff after surviving the wide-transition energy valley.
            // [STRATEGY TEST] Original was SampleId.CROWD_HEY — restore if preferred.
            MixStrategy.WIDE_TRANSITION  -> SampleId.AIR_HORN
        } ?: return

        triggerSample(sample)
        Log.d(TAG, "Auto: drop completed [${strategy.name}] → ${sample.name}")
    }
}