package com.engfred.musicplayer.feature_dj_mix.data.sampler

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import android.util.Log
import androidx.media3.common.util.UnstableApi
import com.engfred.musicplayer.feature_dj_mix.data.crossfade.CrossfadeEngine
import com.engfred.musicplayer.feature_dj_mix.data.crossfade.CrossfadeEngineState
import com.engfred.musicplayer.feature_dj_mix.data.crossfade.MixStrategy
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Low-latency DJ sampler engine built on Android's [SoundPool].
 *
 * ── Two trigger modes ────────────────────────────────────────────────────────
 * 1. AUTO   — observes [CrossfadeEngine.state] and fires samples automatically
 *             at crossfade lifecycle events (start, mid-mix, completion).
 *             Controlled by [isAutoSamplerEnabled].
 * 2. MANUAL — the DJ Mix UI exposes a pad grid; tapping a pad calls
 *             [triggerSample] directly.
 *
 * ── Architecture notes ───────────────────────────────────────────────────────
 * - [SoundPool] pre-decodes all audio to raw PCM at load time, so each
 *   [triggerSample] fires in < 10 ms — fast enough to feel "live".
 * - Up to [MAX_STREAMS] sounds can overlap simultaneously.
 * - Synthesized samples are generated by [SynthesizedSampleGenerator] on a
 *   background coroutine and loaded into SoundPool once their WAV file is ready.
 * - [SamplerEngine] is a @Singleton; call [initialize] from [DjMixService.onCreate]
 *   and [release] from [DjMixService.releaseAndStop] / [DjMixService.onDestroy].
 * - Call [onSessionStarted] from [DjMixService] when the first track begins playing.
 *
 * ── Auto-trigger map (every strategy has full coverage) ──────────────────────
 *
 *  Strategy          │ On crossfade START  │ Mid-mix (fraction)       │ On DROP (complete)
 *  ──────────────────┼─────────────────────┼──────────────────────────┼────────────────────
 *  TRANSPARENT       │ DJ_SCRATCH          │ —                        │ — (silence = effect)
 *  SMOOTH            │ RISER_SWEEP         │ STUTTER_HIT   (50%)      │ AIR_HORN
 *  POWER_MIX         │ WHITE_NOISE_UP      │ IMPACT_HIT    (35%)      │ AIR_HORN
 *  HARMONIC          │ REWIND_SWEEP        │ —                        │ CROWD_HEY
 *  WIDE_TRANSITION   │ SIREN               │ STUTTER_HIT   (45%)      │ CROWD_HEY
 *  ────────────────────────────────────────────────────────────────────────────────────────
 *  Session start     │ AIR_HORN (once — fired via [onSessionStarted])
 *
 * ── DJ reasoning ─────────────────────────────────────────────────────────────
 * TRANSPARENT: Perfect beatmatch — a quick scratch says "I see you" without drama.
 *              No drop sound needed; the seamless blend IS the drop.
 *
 * SMOOTH: Riser builds anticipation. Stutter at the midpoint pumps energy during
 *         the bass-kill gap. Air horn celebrates the clean landing.
 *
 * POWER_MIX: White noise sweeps in aggression. Impact hit at bass-kill threshold
 *            punches the crowd as low-end drops out. Air horn at the drop.
 *
 * HARMONIC: A downward rewind sweep primes the ear for the tempo shift —
 *           "time is bending". Crowd Hey at landing celebrates the harmonic lock.
 *
 * WIDE_TRANSITION: Siren announces the energy valley (>15 BPM jump = dramatic moment).
 *                  Stutter at mid fills the silence when both tracks feel disconnected.
 *                  Crowd Hey at drop rewards the crowd for surviving the valley.
 */
@UnstableApi
@Singleton
class SamplerEngine @Inject constructor(
    @param:ApplicationContext private val context: Context,
    private val crossfadeEngine: CrossfadeEngine,
    private val synthesizer: SynthesizedSampleGenerator
) {

    companion object {
        private const val TAG         = "SamplerEngine"
        private const val MAX_STREAMS = 6 // bumped to allow session-horn + mid + drop overlap

        // Per-strategy mid-crossfade trigger thresholds (fraction of crossfade progress).
        // These intentionally differ from the bass-kill EQ thresholds in MixDecisionEngine
        // — the sampler fires at a musically optimal moment, the EQ at a technical one.
        private const val MID_FRACTION_SMOOTH          = 0.50f // halfway — peak energy build
        private const val MID_FRACTION_POWER_MIX       = 0.35f // matches BASS_KILL_POWER_MIX
        private const val MID_FRACTION_WIDE_TRANSITION = 0.45f // just before energy valley nadir

        private const val SESSION_HORN_POLL_MS    = 20L
        private const val SESSION_HORN_TIMEOUT_MS = 600L
    }

    // ── SoundPool state ───────────────────────────────────────────────────────

    private var soundPool: SoundPool? = null

    /** Maps SampleId → SoundPool sound ID returned by SoundPool.load(). */
    private val soundIds     = mutableMapOf<SampleId, Int>()

    /** Tracks which SoundPool sound IDs have fully decoded and are ready to play. */
    private val loadedSounds = mutableSetOf<Int>()

    // ── Settings ──────────────────────────────────────────────────────────────

    /** When false the engine is silent on all auto-triggers; manual pads still work. */
    var isAutoSamplerEnabled: Boolean = true

    /** Volume applied to every sample playback (0.0 – 1.0). */
    var sampleVolume: Float = 0.80f

    // ── Internal ──────────────────────────────────────────────────────────────

    private var samplerScope  = CoroutineScope(SupervisorJob() + Dispatchers.Default)
    private var observerJob: Job? = null

    @Volatile private var isInitialized = false
    @Volatile private var isReleased    = false

    /**
     * Guards against firing the mid-crossfade sampler more than once per transition.
     * Reset to false each time isCrossfading flips true → false → true.
     */
    @Volatile private var midTriggerFiredForCurrentCrossfade = false

    val isReady: Boolean get() = isInitialized && !isReleased

    // ═════════════════════════════════════════════════════════════════════════
    // INITIALISATION / RELEASE
    // ═════════════════════════════════════════════════════════════════════════

    fun initialize() {
        if (isInitialized) return

        if (isReleased) {
            samplerScope  = CoroutineScope(SupervisorJob() + Dispatchers.Default)
            isReleased    = false
            soundIds.clear()
            loadedSounds.clear()
            midTriggerFiredForCurrentCrossfade = false
        }

        val audioAttrs = AudioAttributes.Builder()
            .setUsage(AudioAttributes.USAGE_MEDIA)
            .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
            .build()

        soundPool = SoundPool.Builder()
            .setMaxStreams(MAX_STREAMS)
            .setAudioAttributes(audioAttrs)
            .build()
            .also { pool ->
                pool.setOnLoadCompleteListener { _, soundId, status ->
                    if (status == 0) {
                        loadedSounds.add(soundId)
                        val name = soundIds.entries.firstOrNull { it.value == soundId }?.key?.name
                        Log.d(TAG, "Loaded: $name (soundId=$soundId)")
                    } else {
                        Log.e(TAG, "Load failed: soundId=$soundId status=$status")
                    }
                }
            }

        loadAllSamples()
        startAutoTriggerObserver()
        isInitialized = true
        Log.d(TAG, "initialize: SamplerEngine ready")
    }

    fun release() {
        if (isReleased) return
        isReleased = true
        observerJob?.cancel()
        samplerScope.cancel()
        soundPool?.release()
        soundPool    = null
        soundIds.clear()
        loadedSounds.clear()
        isInitialized = false
        Log.d(TAG, "release: SamplerEngine released")
    }

    // ═════════════════════════════════════════════════════════════════════════
    // SAMPLE LOADING
    // ═════════════════════════════════════════════════════════════════════════

    private fun loadAllSamples() {
        val pool = soundPool ?: return

        // ── Asset-based samples (downloaded CC0 OGG files) ────────────────────
        SampleId.entries.forEach { sampleId ->
            val path = sampleId.assetPath ?: return@forEach
            try {
                val afd     = context.assets.openFd(path)
                val soundId = pool.load(afd, 1)
                afd.close()
                if (soundId > 0) {
                    soundIds[sampleId] = soundId
                    Log.d(TAG, "Queued asset load: ${sampleId.name} → soundId=$soundId")
                } else {
                    Log.e(TAG, "SoundPool.load returned 0 for ${sampleId.name} — check asset path: $path")
                }
            } catch (e: Exception) {
                Log.e(TAG, "Asset load failed for ${sampleId.name}: ${e.message}")
            }
        }

        // ── Synthesized samples ───────────────────────────────────────────────
        samplerScope.launch(Dispatchers.IO) {
            SampleId.entries
                .filter { it.assetPath == null }
                .forEach { sampleId ->
                    try {
                        val file    = synthesizer.getOrGenerate(sampleId)
                        val soundId = pool.load(file.absolutePath, 1)
                        if (soundId > 0) {
                            soundIds[sampleId] = soundId
                            Log.d(TAG, "Queued synthesized load: ${sampleId.name} → soundId=$soundId")
                        } else {
                            Log.e(TAG, "SoundPool.load returned 0 for synthesized ${sampleId.name}")
                        }
                    } catch (e: Exception) {
                        Log.e(TAG, "Synthesized load failed for ${sampleId.name}: ${e.message}")
                    }
                }
        }
    }

    // ═════════════════════════════════════════════════════════════════════════
    // PUBLIC API
    // ═════════════════════════════════════════════════════════════════════════

    /**
     * Plays [sampleId] immediately at [sampleVolume].
     * Safe to call from any thread — SoundPool.play() is thread-safe.
     *
     * Returns the SoundPool stream ID (> 0 on success, 0 on failure).
     */
    fun triggerSample(sampleId: SampleId): Int {
        if (isReleased) return 0
        val pool    = soundPool ?: return 0
        val soundId = soundIds[sampleId] ?: run {
            Log.w(TAG, "triggerSample: ${sampleId.name} not loaded yet — skipping")
            return 0
        }
        if (soundId !in loadedSounds) {
            Log.w(TAG, "triggerSample: ${sampleId.name} still decoding — skipping")
            return 0
        }
        val vol      = sampleVolume.coerceIn(0f, 1f)
        val streamId = pool.play(soundId, vol, vol, 1, 0, 1.0f)
        Log.d(TAG, "triggerSample: ${sampleId.name} streamId=$streamId vol=$vol")
        return streamId
    }

    /**
     * Stops a specific sample stream returned by [triggerSample].
     */
    fun stopSample(streamId: Int) {
        if (isReleased || streamId <= 0) return
        soundPool?.stop(streamId)
        Log.d(TAG, "stopSample: streamId=$streamId")
    }

    /**
     * Immediately pauses ALL currently playing sample streams.
     * Does not affect the CrossfadeEngine or ExoPlayer music.
     */
    fun stopAllSamples() {
        if (isReleased) return
        soundPool?.autoPause()
        Log.d(TAG, "stopAllSamples: autoPause called")
    }

    /**
     * Called once per DJ session when the first track begins playing.
     *
     * Race-condition fix: SoundPool.load() is async. On first launch observeFirstPlay()
     * in DjMixService fires ~146ms before the OGG decoder finishes (confirmed by logcat),
     * causing triggerSample() to log "still decoding" and produce silence.
     *
     * Fix: fast-path plays immediately if already decoded (all launches after the first).
     * Slow-path polls loadedSounds every SESSION_HORN_POLL_MS until the asset is ready
     * or SESSION_HORN_TIMEOUT_MS elapses. Typical slow-path wait: 20-40ms (1-2 poll
     * cycles after the decoder finishes).
     */
    fun onSessionStarted() {
        if (isReleased || !isAutoSamplerEnabled) return

        // Fast path: already loaded - play immediately (common on all launches after first).
        val soundId = soundIds[SampleId.AIR_HORN]
        if (soundId != null && soundId in loadedSounds) {
            triggerSample(SampleId.AIR_HORN)
            Log.d(TAG, "onSessionStarted: AIR_HORN fired immediately - DJ Mix is live")
            return
        }

        // Slow path: decoder hasn't finished yet - wait and retry.
        Log.d(TAG, "onSessionStarted: AIR_HORN not decoded yet - waiting (slow path)")
        samplerScope.launch {
            val startMs = System.currentTimeMillis()
            val sid     = soundIds[SampleId.AIR_HORN] ?: run {
                Log.w(TAG, "onSessionStarted: AIR_HORN has no soundId - asset load may have failed")
                return@launch
            }
            while (!isReleased) {
                if (sid in loadedSounds) {
                    triggerSample(SampleId.AIR_HORN)
                    Log.d(TAG, "onSessionStarted: AIR_HORN fired after " +
                            "${System.currentTimeMillis() - startMs}ms wait - DJ Mix is live")
                    return@launch
                }
                if (System.currentTimeMillis() - startMs > SESSION_HORN_TIMEOUT_MS) {
                    Log.w(TAG, "onSessionStarted: AIR_HORN timed out after ${SESSION_HORN_TIMEOUT_MS}ms - skipping")
                    return@launch
                }
                delay(SESSION_HORN_POLL_MS)
            }
        }
    }

    // ═════════════════════════════════════════════════════════════════════════
    // AUTO-TRIGGER OBSERVER
    // ═════════════════════════════════════════════════════════════════════════

    /**
     * Collects [CrossfadeEngine.state] on the Default dispatcher and fires samples
     * at three lifecycle points per crossfade:
     *
     *  1. **START**  — isCrossfading flips false → true
     *  2. **MID**    — crossfadeProgressFraction crosses the per-strategy threshold
     *                  (only for SMOOTH, POWER_MIX, WIDE_TRANSITION)
     *  3. **DROP**   — isCrossfading flips true → false AND currentTrack.id changed
     *
     * [midTriggerFiredForCurrentCrossfade] ensures the mid-sample fires exactly once
     * even if the state flow emits rapidly around the threshold value.
     */
    private fun startAutoTriggerObserver() {
        observerJob?.cancel()
        observerJob = samplerScope.launch {
            var prev: CrossfadeEngineState? = null

            crossfadeEngine.state.collect { current ->
                val previous = prev
                prev = current

                if (!isAutoSamplerEnabled) return@collect

                // ── 1. Crossfade just STARTED ─────────────────────────────────
                if (previous?.isCrossfading == false && current.isCrossfading) {
                    midTriggerFiredForCurrentCrossfade = false
                    onCrossfadeStarted(current.currentMixStrategy)
                }

                // ── 2. Mid-crossfade threshold crossed ────────────────────────
                if (current.isCrossfading && !midTriggerFiredForCurrentCrossfade) {
                    val midTrigger = midTriggerFor(current.currentMixStrategy)
                    if (midTrigger != null) {
                        val prevFraction = previous?.crossfadeProgressFraction ?: 0f
                        val currFraction = current.crossfadeProgressFraction
                        if (prevFraction < midTrigger.first && currFraction >= midTrigger.first) {
                            midTriggerFiredForCurrentCrossfade = true
                            triggerSample(midTrigger.second)
                            Log.d(TAG, "Auto: mid-mix [${current.currentMixStrategy}] @ " +
                                    "${(midTrigger.first * 100).toInt()}% → ${midTrigger.second.name}")
                        }
                    }
                }

                // ── 3. Crossfade just COMPLETED (track changed) ───────────────
                val trackChanged = previous?.currentTrack?.id != current.currentTrack?.id
                if (previous?.isCrossfading == true && !current.isCrossfading && trackChanged) {
                    onDropCompleted(previous.currentMixStrategy)
                }
            }
        }
    }

    /**
     * Returns the (threshold fraction, sample) pair for strategies that have a
     * mid-crossfade trigger, or null for strategies that do not.
     */
    private fun midTriggerFor(strategy: MixStrategy): Pair<Float, SampleId>? = when (strategy) {
        MixStrategy.SMOOTH          -> MID_FRACTION_SMOOTH          to SampleId.STUTTER_HIT
        MixStrategy.POWER_MIX       -> MID_FRACTION_POWER_MIX       to SampleId.IMPACT_HIT
        MixStrategy.WIDE_TRANSITION -> MID_FRACTION_WIDE_TRANSITION to SampleId.STUTTER_HIT
        MixStrategy.TRANSPARENT,
        MixStrategy.HARMONIC        -> null
    }

    // ── Lifecycle callbacks ───────────────────────────────────────────────────

    private fun onCrossfadeStarted(strategy: MixStrategy) {
        val sample = when (strategy) {
            // Quick scratch: subtle professional acknowledgment of the beatmatch.
            MixStrategy.TRANSPARENT     -> SampleId.DJ_SCRATCH

            // Classic rising sweep: tells the crowd "something's coming".
            MixStrategy.SMOOTH          -> SampleId.RISER_SWEEP

            // Aggressive white noise sweep in: primes the ear for the power mix.
            MixStrategy.POWER_MIX       -> SampleId.WHITE_NOISE_UP

            // Downward vinyl brake: "time is shifting" — perfect for half/double-time.
            MixStrategy.HARMONIC        -> SampleId.REWIND_SWEEP

            // Siren: announces the energy valley — the BPM jump IS the moment.
            MixStrategy.WIDE_TRANSITION -> SampleId.SIREN
        }
        triggerSample(sample)
        Log.d(TAG, "Auto: crossfade started [${strategy.name}] → ${sample.name}")
    }

    private fun onDropCompleted(strategy: MixStrategy) {
        val sample = when (strategy) {
            // Seamless blend — silence respects the transparency. No drop sound needed.
            MixStrategy.TRANSPARENT     -> null

            // Air horn: classic crowd-pleaser on a clean SMOOTH landing.
            MixStrategy.SMOOTH          -> SampleId.AIR_HORN

            // Air horn: rewards the crowd after the bass-kill power mix.
            MixStrategy.POWER_MIX       -> SampleId.AIR_HORN

            // Crowd Hey: celebrates the harmonic lock — the crowd earned this.
            MixStrategy.HARMONIC        -> SampleId.CROWD_HEY

            // Crowd Hey: payoff after surviving the wide-transition energy valley.
            MixStrategy.WIDE_TRANSITION -> SampleId.CROWD_HEY
        } ?: return

        triggerSample(sample)
        Log.d(TAG, "Auto: drop completed [${strategy.name}] → ${sample.name}")
    }
}