package com.engfred.musicplayer.feature_dj_mix.data.sampler

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import android.util.Log
import androidx.media3.common.util.UnstableApi
import com.engfred.musicplayer.feature_dj_mix.data.crossfade.CrossfadeEngine
import com.engfred.musicplayer.feature_dj_mix.data.crossfade.CrossfadeEngineState
import com.engfred.musicplayer.feature_dj_mix.data.crossfade.MixStrategy
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Low-latency DJ sampler engine built on Android's [SoundPool].
 *
 * ── Two trigger modes ────────────────────────────────────────────────────────
 * 1. AUTO   — observes [CrossfadeEngine.state] and fires samples automatically
 *             at crossfade lifecycle events (start, bass-kill zone, completion).
 *             Controlled by [isAutoSamplerEnabled].
 * 2. MANUAL — the DJ Mix UI exposes a pad grid; tapping a pad calls
 *             [triggerSample] directly.
 *
 * ── Architecture notes ───────────────────────────────────────────────────────
 * - [SoundPool] pre-decodes all audio to raw PCM at load time, so each
 *   [triggerSample] fires in < 10 ms — fast enough to feel "live".
 * - Up to [MAX_STREAMS] sounds can overlap simultaneously (e.g. riser + music).
 * - Synthesized samples are generated by [SynthesizedSampleGenerator] on a
 *   background coroutine and loaded into SoundPool once their WAV file is ready.
 * - [SamplerEngine] is a @Singleton; call [initialize] from [DjMixService.onCreate]
 *   and [release] from [DjMixService.releaseAndStop] / [DjMixService.onDestroy].
 *
 * ── Auto-trigger map ─────────────────────────────────────────────────────────
 *
 *  Strategy          │ On crossfade START │ Bass-kill zone (≈40%) │ On DROP (complete)
 *  ──────────────────┼────────────────────┼───────────────────────┼───────────────────
 *  TRANSPARENT       │ —                  │ —                     │ —
 *  SMOOTH            │ RISER_SWEEP        │ —                     │ AIR_HORN
 *  POWER_MIX         │ WHITE_NOISE_UP     │ IMPACT_HIT            │ AIR_HORN
 *  HARMONIC          │ —                  │ —                     │ —
 *  WIDE_TRANSITION   │ SIREN              │ —                     │ CROWD_HEY
 */
@UnstableApi
@Singleton
class SamplerEngine @Inject constructor(
    @param:ApplicationContext private val context: Context,
    private val crossfadeEngine: CrossfadeEngine,
    private val synthesizer: SynthesizedSampleGenerator
) {

    companion object {
        private const val TAG         = "SamplerEngine"
        private const val MAX_STREAMS = 4

        // crossfadeProgressFraction threshold at which we consider the bass-kill
        // zone "active" for POWER_MIX — matches MixDecisionEngine.BASS_KILL_POWER_MIX.
        private const val BASS_KILL_FRACTION = 0.35f
    }

    // ── SoundPool state ───────────────────────────────────────────────────────

    private var soundPool: SoundPool? = null

    /**
     * Maps SampleId → SoundPool sound ID returned by SoundPool.load().
     * A sound ID of 0 means the load call failed.
     */
    private val soundIds     = mutableMapOf<SampleId, Int>()

    /**
     * Tracks which SoundPool sound IDs have fully decoded and are ready to play.
     * Populated by [SoundPool.OnLoadCompleteListener].
     */
    private val loadedSounds = mutableSetOf<Int>()

    // ── Settings (write from ViewModel / DjMixService) ────────────────────────

    /** When false the engine is silent on all auto-triggers; manual pads still work. */
    var isAutoSamplerEnabled: Boolean = true

    /** Volume applied to every sample playback (0.0 – 1.0). */
    var sampleVolume: Float = 0.80f

    // ── Internal ──────────────────────────────────────────────────────────────

    private var samplerScope  = CoroutineScope(SupervisorJob() + Dispatchers.Default)
    private var observerJob: Job? = null

    @Volatile private var isInitialized = false
    @Volatile private var isReleased    = false

    val isReady: Boolean get() = isInitialized && !isReleased

    // ═════════════════════════════════════════════════════════════════════════
    // INITIALISATION / RELEASE
    // ═════════════════════════════════════════════════════════════════════════

    fun initialize() {
        if (isInitialized) return

        if (isReleased) {
            // Allow re-initialisation after release (e.g. user re-enters DJ mode)
            samplerScope  = CoroutineScope(SupervisorJob() + Dispatchers.Default)
            isReleased    = false
            soundIds.clear()
            loadedSounds.clear()
        }

        val audioAttrs = AudioAttributes.Builder()
            .setUsage(AudioAttributes.USAGE_MEDIA)
            .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
            .build()

        soundPool = SoundPool.Builder()
            .setMaxStreams(MAX_STREAMS)
            .setAudioAttributes(audioAttrs)
            .build()
            .also { pool ->
                pool.setOnLoadCompleteListener { _, soundId, status ->
                    if (status == 0) {
                        loadedSounds.add(soundId)
                        val name = soundIds.entries.firstOrNull { it.value == soundId }?.key?.name
                        Log.d(TAG, "Loaded: $name (soundId=$soundId)")
                    } else {
                        Log.e(TAG, "Load failed: soundId=$soundId status=$status")
                    }
                }
            }

        loadAllSamples()
        startAutoTriggerObserver()
        isInitialized = true
        Log.d(TAG, "initialize: SamplerEngine ready")
    }

    fun release() {
        if (isReleased) return
        isReleased = true
        observerJob?.cancel()
        samplerScope.cancel()
        soundPool?.release()
        soundPool    = null
        soundIds.clear()
        loadedSounds.clear()
        isInitialized = false
        Log.d(TAG, "release: SamplerEngine released")
    }

    // ═════════════════════════════════════════════════════════════════════════
    // SAMPLE LOADING
    // ═════════════════════════════════════════════════════════════════════════

    private fun loadAllSamples() {
        val pool = soundPool ?: return

        // ── Asset-based samples (downloaded CC0 OGG files) ────────────────────
        SampleId.entries.forEach { sampleId ->
            val path = sampleId.assetPath ?: return@forEach
            try {
                val afd    = context.assets.openFd(path)
                val soundId = pool.load(afd, 1)
                afd.close()
                if (soundId > 0) {
                    soundIds[sampleId] = soundId
                    Log.d(TAG, "Queued asset load: ${sampleId.name} → soundId=$soundId")
                } else {
                    Log.e(TAG, "SoundPool.load returned 0 for ${sampleId.name} — check asset path: $path")
                }
            } catch (e: Exception) {
                Log.e(TAG, "Asset load failed for ${sampleId.name}: ${e.message}")
            }
        }

        // ── Synthesized samples (generated in background, then loaded) ────────
        samplerScope.launch(Dispatchers.IO) {
            SampleId.entries
                .filter { it.assetPath == null }
                .forEach { sampleId ->
                    try {
                        val file    = synthesizer.getOrGenerate(sampleId)
                        val soundId = pool.load(file.absolutePath, 1)
                        if (soundId > 0) {
                            soundIds[sampleId] = soundId
                            Log.d(TAG, "Queued synthesized load: ${sampleId.name} → soundId=$soundId")
                        } else {
                            Log.e(TAG, "SoundPool.load returned 0 for synthesized ${sampleId.name}")
                        }
                    } catch (e: Exception) {
                        Log.e(TAG, "Synthesized load failed for ${sampleId.name}: ${e.message}")
                    }
                }
        }
    }

    // ═════════════════════════════════════════════════════════════════════════
    // PUBLIC API
    // ═════════════════════════════════════════════════════════════════════════

    /**
     * Plays [sampleId] immediately at [sampleVolume].
     * Safe to call from any thread — SoundPool.play() is thread-safe.
     *
     * Returns the SoundPool stream ID (> 0 on success, 0 on failure).
     * The caller can store this to stop the sound early via [stopSample].
     */
    fun triggerSample(sampleId: SampleId): Int {
        if (isReleased) return 0
        val pool    = soundPool ?: return 0
        val soundId = soundIds[sampleId] ?: run {
            Log.w(TAG, "triggerSample: ${sampleId.name} not loaded yet — skipping")
            return 0
        }
        if (soundId !in loadedSounds) {
            Log.w(TAG, "triggerSample: ${sampleId.name} still decoding — skipping")
            return 0
        }
        val vol      = sampleVolume.coerceIn(0f, 1f)
        val streamId = pool.play(soundId, vol, vol, 1, 0, 1.0f)
        Log.d(TAG, "triggerSample: ${sampleId.name} streamId=$streamId vol=$vol")
        return streamId
    }

    /**
     * Stops a specific sample stream returned by [triggerSample].
     * Useful if a long sample (e.g. SIREN) needs to be cut short.
     */
    fun stopSample(streamId: Int) {
        if (isReleased || streamId <= 0) return
        soundPool?.stop(streamId)
        Log.d(TAG, "stopSample: streamId=$streamId")
    }

    /**
     * Immediately stops ALL currently playing sample streams.
     * Does not affect the CrossfadeEngine or ExoPlayer music.
     */
    fun stopAllSamples() {
        if (isReleased) return
        val pool = soundPool ?: return
        soundIds.values.toSet().forEach { soundId ->
            // SoundPool has no "stop by soundId" API — we autoPause/autoResume instead.
        }
        pool.autoPause()
        Log.d(TAG, "stopAllSamples: autoPause called")
    }

    // ═════════════════════════════════════════════════════════════════════════
    // AUTO-TRIGGER OBSERVER
    // ═════════════════════════════════════════════════════════════════════════

    /**
     * Collects [CrossfadeEngine.state] on the Default dispatcher and compares
     * each emission with the previous one to detect lifecycle transitions.
     *
     * We deliberately do NOT use [Dispatchers.Main] here — SoundPool.play() is
     * thread-safe and we don't want to block the UI thread.
     */
    private fun startAutoTriggerObserver() {
        observerJob?.cancel()
        observerJob = samplerScope.launch {
            var prev: CrossfadeEngineState? = null

            crossfadeEngine.state.collect { current ->
                val previous = prev
                prev = current

                if (!isAutoSamplerEnabled) return@collect

                // ── Crossfade just STARTED ────────────────────────────────────
                if (previous?.isCrossfading == false && current.isCrossfading) {
                    onCrossfadeStarted(current.currentMixStrategy)
                }

                // ── Crossfade just COMPLETED (swap done, track changed) ───────
                val trackChanged = previous?.currentTrack?.id != current.currentTrack?.id
                if (previous?.isCrossfading == true && !current.isCrossfading && trackChanged) {
                    onDropCompleted(previous.currentMixStrategy)
                }

                // ── Bass-kill zone crossed (POWER_MIX only) ───────────────────
                if (current.isCrossfading && current.currentMixStrategy == MixStrategy.POWER_MIX) {
                    val prevFraction = previous?.crossfadeProgressFraction ?: 0f
                    val currFraction = current.crossfadeProgressFraction
                    if (prevFraction < BASS_KILL_FRACTION && currFraction >= BASS_KILL_FRACTION) {
                        triggerSample(SampleId.IMPACT_HIT)
                        Log.d(TAG, "Auto: bass-kill zone → IMPACT_HIT")
                    }
                }
            }
        }
    }

    private fun onCrossfadeStarted(strategy: MixStrategy) {
        val sample = when (strategy) {
            MixStrategy.TRANSPARENT     -> null          // silky smooth — no sound needed
            MixStrategy.SMOOTH          -> SampleId.RISER_SWEEP
            MixStrategy.POWER_MIX       -> SampleId.WHITE_NOISE_UP
            MixStrategy.HARMONIC        -> null          // harmonic lock IS the effect
            MixStrategy.WIDE_TRANSITION -> SampleId.SIREN
        } ?: return

        triggerSample(sample)
        Log.d(TAG, "Auto: crossfade started [${strategy.name}] → ${sample.name}")
    }

    private fun onDropCompleted(strategy: MixStrategy) {
        val sample = when (strategy) {
            MixStrategy.TRANSPARENT     -> null
            MixStrategy.SMOOTH          -> SampleId.AIR_HORN
            MixStrategy.POWER_MIX       -> SampleId.AIR_HORN
            MixStrategy.HARMONIC        -> null
            MixStrategy.WIDE_TRANSITION -> SampleId.CROWD_HEY
        } ?: return

        triggerSample(sample)
        Log.d(TAG, "Auto: drop completed [${strategy.name}] → ${sample.name}")
    }
}