package com.engfred.musicplayer.core.ui.theme

import androidx.compose.ui.graphics.Color

// --- FROST (LIGHT) ---
val FrostPrimary = Color(0xFF00B8F4)
val FrostOnPrimary = Color(0xFF000000)
val FrostPrimaryContainer = Color(0xFF0288D1)
val FrostOnPrimaryContainer = Color(0xFFFFFFFF)
val FrostSecondary = Color(0xFFB2EBF2)
val FrostOnSecondary = Color(0xFF000000)
val FrostSecondaryContainer = Color(0xFF4DD0E1)
val FrostOnSecondaryContainer = Color(0xFF000000)
val FrostTertiary = Color(0xFF005AC1)
val FrostOnTertiary = Color(0xFFFFFFFF)
val FrostTertiaryContainer = Color(0xFFD8E2FF)
val FrostOnTertiaryContainer = Color(0xFF001A41)
val FrostBackground = Color(0xFFF9F9F9)
val FrostOnBackground = Color(0xFF212121)
val FrostSurface = Color(0xFFF5F5F5)
val FrostOnSurface = Color(0xFF212121)
val FrostSurfaceVariant = Color(0xFFE0F7FA)
val FrostOnSurfaceVariant = Color(0xFF004D40)
val FrostError = Color(0xFFFF5252)
val FrostOnError = Color(0xFFFFFFFF)
val FrostOutline = Color(0xFFB0BEC5)

// --- DEFAULT DARK ---
val DarkPrimary = Color(0xFFBB86FC)
val DarkOnPrimary = Color(0xFF000000)
val DarkPrimaryContainer = Color(0xFF3700B3)
val DarkOnPrimaryContainer = Color(0xFFFFFFFF)
val DarkSecondary = Color(0xFF03DAC6)
val DarkOnSecondary = Color(0xFF000000)
val DarkSecondaryContainer = Color(0xFF018786)
val DarkOnSecondaryContainer = Color(0xFFFFFFFF)
val DarkTertiary = Color(0xFFCF6679) // Added M2 classic secondary/error blend
val DarkOnTertiary = Color(0xFF000000)
val DarkTertiaryContainer = Color(0xFF8C1D18)
val DarkOnTertiaryContainer = Color(0xFFFFFFFF)
val DarkBackground = Color(0xFF121212)
val DarkOnBackground = Color(0xFFFFFFFF)
val DarkSurface = Color(0xFF121212)
val DarkOnSurface = Color(0xFFFFFFFF)
val DarkSurfaceVariant = Color(0xFF424242)
val DarkOnSurfaceVariant = Color(0xFFBDBDBD)
val DarkError = Color(0xFFCF6679)
val DarkOnError = Color(0xFF000000)
val DarkOutline = Color(0xFFBDBDBD)

// --- DEEP BLUE ---
val DeepBluePrimary = Color(0xFF007ACC)
val DeepBlueOnPrimary = Color(0xFFFFFFFF)
val DeepBluePrimaryContainer = Color(0xFF005F99)
val DeepBlueOnPrimaryContainer = Color(0xFFFFFFFF)
val DeepBlueSecondary = Color(0xFF00CC99)
val DeepBlueOnSecondary = Color(0xFF000000)
val DeepBlueSecondaryContainer = Color(0xFF009973)
val DeepBlueOnSecondaryContainer = Color(0xFFFFFFFF)
val DeepBlueTertiary = Color(0xFFFFB300) // Added warm amber/gold for premium contrast
val DeepBlueOnTertiary = Color(0xFF000000)
val DeepBlueTertiaryContainer = Color(0xFFB27D00)
val DeepBlueOnTertiaryContainer = Color(0xFFFFFFFF)
val DeepBlueBackground = Color(0xFF0A192F)
val DeepBlueOnBackground = Color(0xFFE0F2F7)
val DeepBlueSurface = Color(0xFF1A2B42)
val DeepBlueOnSurface = Color(0xFFE0F2F7)
val DeepBlueSurfaceVariant = Color(0xFF2A3C53)
val DeepBlueOnSurfaceVariant = Color(0xFFB0C4DE)
val DeepBlueError = Color(0xFFE57373)
val DeepBlueOnError = Color(0xFF000000)
val DeepBlueOutline = Color(0xFF4A6572)

// --- NEON PULSE ---
val NeonPrimary = Color(0xFFFF00FF)
val NeonOnPrimary = Color(0xFF000000)
val NeonPrimaryContainer = Color(0xFFAA00AA)
val NeonOnPrimaryContainer = Color(0xFFFFFFFF)
val NeonSecondary = Color(0xFF39FF14)
val NeonOnSecondary = Color(0xFF000000)
val NeonSecondaryContainer = Color(0xFF00CC00)
val NeonOnSecondaryContainer = Color(0xFF000000)
val NeonTertiary = Color(0xFF00FFFF) // Added Cyberpunk Cyan to complete the triad
val NeonOnTertiary = Color(0xFF000000)
val NeonTertiaryContainer = Color(0xFF008888)
val NeonOnTertiaryContainer = Color(0xFFFFFFFF)
val NeonBackground = Color(0xFF000000)
val NeonOnBackground = Color(0xFFF0F0F0)
val NeonSurface = Color(0xFF0F0F0F)
val NeonOnSurface = Color(0xFFE0F7FA)
val NeonSurfaceVariant = Color(0xFF1A1A1A)
val NeonOnSurfaceVariant = Color(0xFF80D8FF)
val NeonError = Color(0xFFFF1744)
val NeonOnError = Color(0xFFFFFFFF)
val NeonOutline = Color(0xFF9C27B0)

// --- SUNSET GROOVE ---
val SunsetPrimary = Color(0xFFFF8A65)
val SunsetOnPrimary = Color(0xFF000000)
val SunsetPrimaryContainer = Color(0xFFFF7043)
val SunsetOnPrimaryContainer = Color(0xFFFFFFFF)
val SunsetSecondary = Color(0xFFBA68C8)
val SunsetOnSecondary = Color(0xFF000000)
val SunsetSecondaryContainer = Color(0xFF9C27B0)
val SunsetOnSecondaryContainer = Color(0xFFFFFFFF)
val SunsetTertiary = Color(0xFFFFD54F) // Added Golden yellow to bridge orange and lavender
val SunsetOnTertiary = Color(0xFF000000)
val SunsetTertiaryContainer = Color(0xFFFFA000)
val SunsetOnTertiaryContainer = Color(0xFF000000)
val SunsetBackground = Color(0xFF1E1E1E)
val SunsetOnBackground = Color(0xFFFFE0B2)
val SunsetSurface = Color(0xFF2A2A2A)
val SunsetOnSurface = Color(0xFFFFECB3)
val SunsetSurfaceVariant = Color(0xFF4E342E)
val SunsetOnSurfaceVariant = Color(0xFFD7CCC8)
val SunsetError = Color(0xFFD32F2F)
val SunsetOnError = Color(0xFFFFFFFF)
val SunsetOutline = Color(0xFF795548)